server:
  port: 8091
spring:
  main:
    allow-bean-definition-overriding: true
oss:
  aliyun:
    imagesHost: images
    endPoint: oss-cn-shenzhen.aliyuncs.com
    bucket: hetonghao
    accessKeyId: LTAI4FgBBEeeRTMkVVFkKFEA
    accessKeySecret: tBozzMHsGedyr9KWuQNUiPFu57XP1J